repo_id: "viberec/ML-1M-SASRec"
epochs: 3
train_batch_size: 8192
eval_batch_size: 8192

# Finetune Parameters
alpha: 0.8
learning_rate: 0.00001

# GRPO Specific Parameters
group_size: 16 
kl_beta: 0.1
clip_grad_norm: 1.0
